version: '3'
services:
  frontend:
    build: ./frontend
    ports:
    - "8000:8000"
    links:
    - backend
  backend:
    build: ./backend
    ports:
     - "5000:5000"
  proxy:
    image: nginx
    links:
    - frontend
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
    - "80:80"
